config/routes.rb
Rails.application.routes.draw do
	
	root "welcome#homepage"
	get "/about_us" => "welcome#about_us"

  	devise_for :users
	resources :user, only:[:update]
	
	resources :notifications do
		member do
			put "toggle_solved"
		end
	
		resources :comments
	end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :notification
	belongs_to :user
end

app/models/notification.rb
class Notification < ActiveRecord::Base
	has_attached_file :optional_photo, styles:{thumb:"300x300>", medium:"800x800>"}
	validates_attachment_content_type :optional_photo, content_type:  /\Aimage\/.*\Z/
	before_create :mark_as_unresolved
	has_many :comments
	belongs_to :user

	scope :search_for_user, lambda{|user| where user_id:user.id}
	scope :reversed, lambda{order "created_at DESC"}

	def toggle_solved!
		self.solved = !self.solved
	end

	private

	def mark_as_unresolved
		self.solved = false
		return true
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :notifications
  has_many :comments
  has_attached_file :avatar
  validates_attachment_content_type :avatar, content_type:  /\Aimage\/.*\Z/

  def is_admin?
  	self.permission_level == "Admin"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@comment = Comment.new(comment_params)
		@comment.notification = Notification.find(params[:notification_id])
		@comment.user = current_user
		respond_to do |format|
			if @comment.save
				MainMailer.new_comment(@comment).deliver_now
				format.json{render :show, status: :created, location: @comment.notification }
			else
				format.json { render json: @comment.errors, status: :unprocessable_entity}
			end
		end
	end

	private

	def comment_params
		params.require(:comment).permit(:notification_id, :body)
	end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
	before_action :find_notification, only: [:show, :destroy, :toggle_solved]
	before_action :authenticate_user!, only: [:index, :show]

	#GET /notifications
	def index
		if current_user.is_admin?
			@notifications = Notification.all
		else
			@notifications = Notification.search_for_user current_user
		end
		@paged_notifications = @notifications.reversed.paginate page: params[:page], per_page:4
	end

	#GET /notifications/new
	def new
		@notification = Notification.new
	end

	#GET /notification/:id
	def show
		@notification.user = User.find(@notification.user_id) unless @notification.user.nil?
	end

	#POST /notification
	def create
		@notification = Notification.new notification_params
		if current_user
			@notification.user_id = current_user.id
		end
		flash[:notice] = "Aviso creado correctamente. Responderemos en breves a tu problema. ¡Muchas Gracias!."
		@notification.save
		MainMailer.new_notification(@notification).deliver
		redirect_to :root
	end

	#DELETE /notification/:id
	def destroy
		@notification.comments.each{|c| c.destroy}
		@notification.destroy
		redirect_to action:"index"
	end

	def toggle_solved
		@notification.toggle_solved!
		@notification.save
		render nothing: true
	end

	private

	def find_notification
		@notification = Notification.find params[:id]
	end

	def notification_params
		params.require(:notification).permit(:person, :telephone, :city, :street, :number, :appliance, :problem, :optional_photo)
	end

end

app/controllers/user_controller.rb
class UserController < ApplicationController

	def update
		@user = User.find(params[:id])
		@user.update_attribute(:avatar, params[:user][:avatar])
		redirect_to :root
	end

	private

	def user_params
	  params.require(:user).permit(:avatar)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def homepage
	end

	def about_us
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  # A simple way to show error messages for the current devise resource. If you need
  # to customize this method, you can either overwrite it in your application helpers or
  # copy the views to your application.
  #
  # This method is intended to stay simple and it is unlikely that we are going to change
  # it to add more behavior or options.
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation" class="alert alert-danger">
      <button class="close" data-dismiss="alert"><span>&times;</span></button>
      <h5><b>#{sentence}</b></h5>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/notification_helper.rb
module NotificationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Raúl Campos González - Asistencia Técnica</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<%= favicon_link_tag "favicon.ico"%>
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0">
</head>
<body>
	<header>
		<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
			<div class="container-fluid">
				<!-- NAVBAR HEADER -->
				<div class="navbar-header">
					<button class="navbar-toggle collapsed" data-target="#nav-cuerpo" data-toggle="collapse">
						<span class="sr-only">Desplegar/Ocultar</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<%= link_to root_path do%>
						<%= image_tag "logo.png", alt: "Logo", class:"logo" %>
					<% end %>
				</div>
				<!-- NAVBAR BODY -->
				<div class="navbar-collapse collapse" id="nav-cuerpo">
					<ul class="nav navbar-nav">
						<!-- FOR FUTURE DEVELOPMENT -->
						<!-- <li><a href=""><span class="glyphicon glyphicon-star"></span> Novedades</a></li> -->
						<li>
							<%= link_to "/about_us" do%>
								<span class=" glyphicon glyphicon-earphone">
								</span> Contacto
							<% end %>
						</li>
						<% unless user_signed_in? and current_user.permission_level == "Admin" %>
							<li>
								<%= button_to new_notification_path, class:"btn btn-danger navbar-btn", method: :get do %>
									<span class="glyphicon glyphicon-exclamation-sign"></span> Avisar
								<% end %>
							</li>
						<% end %>
						<% if user_signed_in? %>
							<li>
								<%= button_to notifications_path, class:"btn btn-primary navbar-btn", method: :get do%>
									<span class="glyphicon glyphicon-list-alt"></span> Mis avisos
								<% end %>
							</li>
						<% end %>

					</ul>
					<ul class="nav navbar-nav navbar-right">
						<% if user_signed_in? %>
							<% if current_user.avatar_file_name.nil? %>
								<li><%= image_tag "user_default_32x32.jpg", alt: "User avatar default", class:"logo navbar-user" %></li>
							<% else %>
								<li><%= image_tag current_user.avatar.url, alt: "User avatar", class:"logo navbar-user set-32x32"%></li>
							<% end %>
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" role="button" data-toggle="dropdown">
									<%= current_user.email %>
									<span class="caret"></span>
								</a>
								<ul class="dropdown-menu" role="menu">
									<li>
										<%= form_for current_user, :html => { :multipart => true, class:"form-inline" } do |form| %>
											<%= form.file_field :avatar, class:"form-control", style:"padding-bottom:40px;"%>
											<%= form.submit "Cambiar avatar", class:"btn btn-default pull-right", style:"margin:10px 10px 10px;"%>
										<% end %>
									</li>
								</ul>
							</li>
							<li><%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete %></li>
						<% else %>
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" role="button" data-toggle="dropdown">
									<span class="glyphicon glyphicon-user"></span>
									 Usuarios
									<span class="caret"></span>
								</a>
								<ul class="dropdown-menu" role="menu">
									<li><%= link_to "Autenticar", new_user_session_path%></li>
									<li class="divider"></li>
									<li><%= link_to "Registrarse", new_user_registration_path %></li>
								</ul>
							</li>
						<% end %>
					</ul>
				</div>
			</div>
		</nav>
	</header>
	
	<% [notice, alert].each do |x| %>
		<% if x %>
			<div class="alert alert-warning">
				<button class="close" data-dismiss="alert"><span>&times;</span></button>
				<p class="notice"><%= x %></p>
			</div>
		<% end %>
	<% end %>

	<div class="container">
		<%= yield %>
	</div>

	<footer class="footer navbar-inverse">
      <div class="container-fluid text-footer">
        <p class="pull-right">Web personal de Raúl Campos González </p>
      </div>
    </footer>

	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/layouts/panel_property.html.erb
<div class="panel panel-info">
	<div class="panel-heading" role="tab" id="heading<%= id %>">
		<h4 class="panel-title">
			<a href="#collapse<%= id %>" data-toggle="collapse">
				<b><%= attribute %>:</b>
			</a>
		</h4>
	</div>
	<div class="panel-collapse collapse in" id="collapse<%= id %>">
		<div class="panel-body">
			<%= yield %>
		</div>
	</div>
</div>

app/views/notifications/index.html.erb
<div class="col-md-9">
	<% if @notifications.empty? %>
		<%= image_tag "no_notifications.png", alt: "No notifications", class:"img-responsive", style:"margin-top:20px;"%>
	<% else %>
		<div class="well"><h3><span class="glyphicon glyphicon-edit"></span> <b>Notificaciones totales: <%= @notifications.size%></b></h3></div>
		<% @paged_notifications.each do |notification| %>
			<div class="row">
				<div class="col-md-11">
					<article class="notification clearfix">
						<div class="row">
							<%= link_to notification, class:"thumb pull-left" do%>
								<% if notification.optional_photo_file_name.nil? %>
									<%= image_tag "broken_appliance_default.jpg", alt: "Broken appliance", class:"img-thumbnail" %>
								<% else %>
									<%= image_tag notification.optional_photo.url(:thumb), alt: "Broken appliance", class:"img-thumbnail" %>
								<% end %>
							<% end %>
							<h4><b>Dia:</b> <%= notification.created_at.strftime "%d/%m/%Y a las %H:%M" %></h4>
							<h4><b>Persona:</b> <%= notification.person %></h4>
							<h4><b>Teléfono:</b> <%= notification.telephone %> </h4>
							<h4><b>Electrodoméstico</b> <%= notification.appliance %> </h4>
							<h4 class=""><b>Problema:</b></h4>
							<p class="text-justify"> <%= notification.problem %></p>
						</div>
						<div class="row">
							<p class="location">En la localidad <%= notification.city %>, calle <%= notification.street %>, número <%= notification.number %>.</p>
							<div>
								<%= link_to notification, class:"btn btn-info" do%>
									<span class="glyphicon glyphicon-pencil"></span> Comentar 
									<span class="badge"><%= notification.comments.size %></span>
								<% end %>
								<%= render "partials/toggle_solved_and_delete", notification:notification %>
							</div>
						</div>
					</article>
				</div>
			</div>
		<% end %>
	<div class="row">
		<%= will_paginate @paged_notifications, renderer: BootstrapPagination::Rails %>
	</div>
	<% end %>
	
</div>
<div class="col-md-3">
	<%= render "partials/side_bar" %>
</div>

app/views/notifications/new.html.erb
<% unless user_signed_in? %>
	<%= render "partials/dont_have_user_warning" %>
<% end %>

<div class="panel panel-info panel-notification">
	<div class="panel-heading">
		<h2>Formulario de aviso</h1>
	</div>
	<div class="panel-body">
		<div class="alert alert-warning">
			<button class="close" data-dismiss="alert"><span>&times;</span></button>
			*Por favor rellene este formulario en caso de que alguno de sus electrodómesticos tenga un mal funcionamiento. Todos los campos son obligatorios exceptuando la imagen.
		</div>
		<%= form_for(@notification, html:{multipart:true, class:"form-horizontal"}) do |n| %>
			<!-- PERSON -->
			<div class="form-group">
				<%= n.label :person,  "Nombre:", class:"control-label col-md-2" %>
				<div class="col-md-8">
					<%= n.text_field :person, class:"form-control", placeholder:"Nombre o alias", required:true %>
				</div>
			</div>
			<!-- TELEPHONE -->
			<div class="form-group">
				<%= n.label :telephone, "Teléfono:", class:"control-label col-md-2" %>
				<div class="col-md-8">
					<%= n.number_field :telephone, class:"form-control", placeholder:"Teléfono de la persona", min:"1", required:true %>
				</div>
			</div>
			<!-- CITY -->
			<div class="form-group">
				<%= n.label :city, "Localidad:", class:"control-label col-md-2" %>
				<div class="col-md-8">
					<%= n.text_field :city, class:"form-control", placeholder:"Localidad del domicilio", required:true %>
				</div>
			</div>
			<!-- STREET -->
			<div class="form-group">
				<%= n.label :street, "Calle:", class:"control-label col-md-2" %>
				<div class="col-md-8">
					<%= n.text_field :street, class:"form-control", placeholder:"Calle del domicilio", required:true %>
				</div>
			</div>
			<!-- NUMBER -->
			<div class="form-group">
				<%= n.label :number, "Número:", class:"control-label col-md-2" %>
				<div class="col-md-8">
					<%= n.number_field :number, class:"form-control", placeholder:"Número del domicilio", min:"1", required:true %>
				</div>
			</div>
			<!-- APPLIANCE -->
			<div class="form-group">
				<%= n.label :appliance, "Electrodoméstico:", class:"control-label col-md-2" %>
				<div class="col-md-8">
					<%= n.text_field :appliance, class:"form-control", placeholder:"Tipo de electrodomestico", required:true %>
				</div>
			</div>
			<!-- PROBLEM -->
			<div class="form-group">
				<%= n.label :problem, "Problema:", class:"control-label col-md-2" %>
				<div class="col-md-8">
					<%= n.text_area :problem, class:"form-control", placeholder:"Indique los síntomas del mal funcionamiento", required:true %>		
				</div>
			</div>
			<!-- PHOTO -->
			<div class="form-group">
				<%= n.label :optional_photo, "Imagen:", class:"control-label col-md-2" %>
				<div class="col-md-8">
					<%= n.file_field :optional_photo%>		
					<p class="help-block">Una imagen representativa del estado del electrodoméstico (opcional)</p>
				</div>
			</div>
			<!-- SUBMIT -->
			<div class="form-group">
				<div class="col-md-2 col-md-offset-2">
					<%= n.submit "Enviar", class:"btn btn-primary" %>
				</div>
			</div>
		<% end %>
		
	</div>
</div>

app/views/notifications/show.html.erb
<div class="col-md-9">
	<h2 class="text-primary"><span class="glyphicon glyphicon-edit"></span> Información de aviso 
		<small class="label-toggle-solved">
		<% if @notification.solved %>
			<span class="label label-success">Resuelto</span>
		<% else %>
			<span class="label label-danger">Sin resolver</span>
		<% end %>
		</small>
	</h2>
	<br>
	<div class="panel-group" id="accordion" role="tablist">
		<%= render layout:"partials/panel_property", locals:{attribute:"Día", id:1} do%>
			<%= @notification.created_at.strftime "%m/%d/%Y a las %H:%M" %>
		<% end %>
		<%= render layout:"partials/panel_property", locals:{attribute:"Persona", id:2} do%>
			<%= @notification.person %>
		<% end %>
		<%= render layout:"partials/panel_property", locals:{attribute:"Teléfono", id:3} do%>
			<%= @notification.telephone %>
		<% end %>
		<%= render layout:"partials/panel_property", locals:{attribute:"Localización", id:4} do%>
			<p><%= @notification.city %>, calle <%= @notification.street %>, número <%= @notification.number %></p>
		<% end %>
		<%= render layout:"partials/panel_property", locals:{attribute:"Electrodoméstico", id:5} do%>
			<%= @notification.appliance %>
		<% end %>
		<%= render layout:"partials/panel_property", locals:{attribute:"Problema", id:6} do%>
			<p class="text-justify"> <%= @notification.problem %></p>
		<% end %>
		<% unless @notification.optional_photo_file_name.nil? %>
			<%= render layout:"partials/panel_property", locals:{attribute:"Imagen", id:7} do%>
				<%= image_tag @notification.optional_photo.url, alt: "Broken appliance", class:"img-thumbnail broken-appliance-default" %>
			<% end %>
		<% end %>
	</div>
	<div class="" style="margin-top:20px;margin-bottom:20px;">
		<%= render "partials/toggle_solved_and_delete", notification:@notification %> 
	</div>
	<!-- COMMENTS-FORM -->
	
	<!-- Check if there isn't an user -->
	<% if @notification.user_id.nil? %>
		<% disable_option = true %>
		<% blur_class = "blur" %>
		<div class="well">La persona que registró este aviso no tiene cuenta, por ello los comentarios están desactivados.</div>
	<% end%>

	<div class="panel panel-success <%= blur_class %>">
		<div class="panel-heading"><h4><b>Comentarios</b></h4></div>
		<div class="panel-body" id="comments-box">
			<h5>Nuevo comentario</h5>

			<%= form_for [@notification, Comment.new], remote:true, html:{id:"comments-form", :"data-type" => "json"} do |c|%>
				<div class="form-group">
					<div class="">
						<%= c.text_area :body, class:"form-control", placeholder:"Cuerpo del comentario", required:true, disabled:disable_option %>
					</div>
				</div>
				<div class="form-group">
					<%= c.submit "Enviar", class:"btn btn-primary", disabled:disable_option%>
				</div>
			<% end %> 
			<hr>
			<% @notification.comments.each do |c|%>
				<%= render "partials/comment_skeleton", comment:c, avatar: c.user.avatar, avatar_file_name: c.user.avatar_file_name %>
			<% end %>
		</div>				
	</div>

</div>
<div class="col-md-3">
	<%= render "partials/side_bar" %>
</div>

app/views/partials/_comment_skeleton.html.erb
<div class="media">
	<div class="media-left">
		<% if avatar_file_name.nil? %>
			<%= image_tag "user_default_64x64.jpg", alt: "User avatar default", class:"pull-left img-thumbnail", style:"margin-right:10px;"%>
		<% else %>
			<%= image_tag avatar.url, alt: "User avatar", class:"pull-left img-thumbnail set-64x64", style:"margin-right:10px;" %>
		<% end %>
	</div>

	<div class="media-body">
		<h4 class="media-heading"><%= comment.user.email %></h4>
		<p class="text-justify"><%= comment.body %></p>
	</div>
</div>

	

app/views/partials/_dont_have_user_warning.html.erb
<a href="#modal-register-now" id="btn-modal-register-now" data-toggle="modal" style="display:none;"></a>

<div class="modal fade" id="modal-register-now">
	<div class="modal-dialog">
		<div class="modal-content">
			<!-- MODAL HEADER -->
			<div class="modal-header">
				<button class="close" data-dismiss="modal" aria-hidden="true" type="button">&times;</button>
				<h4>¿No tienes cuenta de usuario?</h4>
			</div>
			<!-- MODAL BODY -->
			<div class="modal-body">
				<p>Si usted se registra podrá recibir por correo cualquier comentario sobre sus avisos y tendrá acceso a la aplicación. Si no lo desea simplemente complete el formulario.</p>
			</div>
			<!-- MODAL FOOTER -->
			<div class="modal-footer">
				<%= link_to new_user_registration_path, options:{}, class:"btn btn-success" do %>
					<span class="glyphicon glyphicon-envelope"></span> 
					Registrarse
				<% end%>
			</div>
		</div>
	</div>
</div>

app/views/partials/_panel_property.html.erb
<div class="panel panel-info">
	<div class="panel-heading" role="tab" id="heading<%= id %>">
		<h4 class="panel-title">
			<a href="#collapse<%= id %>" data-toggle="collapse">
				<b><%= attribute %>:</b>
			</a>
		</h4>
	</div>
	<div class="panel-collapse collapse in" id="collapse<%= id %>">
		<div class="panel-body">
			<%= yield %>
		</div>
	</div>
</div>

app/views/partials/_side_bar.html.erb
<div class="sidebar hidden-xs" style="">
	
	<%= image_tag "side-bar-tool.png", class:"image-center sidebar-img"%>
	<hr>
	<h4 style="" class="text-center"><b>ASISTENCIA TÉCNICA</b></h4>
	<h4 class="text-center"><i>Raúl Campos González</i></h4>
	<hr>
	<%= image_tag "side-bar-top.png", class:"image-center sidebar-img"%>
	<hr>
	<p class="text-justify">
		<span class="glyphicon glyphicon-wrench"></span> 
		<strong>Reparación</strong> a domicilio de todo tipo de electrodomésticos, desde televisores, neveras, ordenadores, lavadoras, etc. 
	</p>
	<hr>
	<%= image_tag "side-bar-middle.png", class:"image-center sidebar-img" %>
	<hr>
	<p class="text-justify">
		<span class="glyphicon glyphicon-home"></span> 
		<strong>Instalación</strong> de antenas para televisión digital terrestre.
	</p>
	<hr>
	<%= image_tag "side-bar-bottom.png", class:"image-center sidebar-img"%>


</div>

app/views/welcome/homepage.html.erb
<div class="row">
	<div class="col-md-12">
		<div class="carousel slide" id="carousel-1" data-ride="carousel">
			<!-- INDEXES -->
			<ol class="carousel-indicators">
				<li data-target="#carousel-1" data-slide-to="0" class="active"></li>
				<li data-target="#carousel-1" data-slide-to="1"></li>
				<li data-target="#carousel-1" data-slide-to="2"></li>
				<li data-target="#carousel-1" data-slide-to="3"></li>
			</ol>
			<!-- CONTENT -->
			<div class="carousel-inner" role="listbox">
				<div class="item active">
					<%= image_tag "carousel-1.jpg", alt: "Broken appliance", class:"img-responsive" %>
				</div>
				<div class="item">
					<%= image_tag "carousel-2.jpg", alt: "Broken appliance", class:"img-responsive" %>
				</div>
				<div class="item">
					<%= image_tag "carousel-3.jpg", alt: "Broken appliance", class:"img-responsive" %>
				</div>
				<div class="item">
					<%= image_tag "carousel-4.jpg", alt: "Broken appliance", class:"img-responsive" %>
				</div>
			</div>
			<!-- CONTROLS -->
			<a href="#carousel-1" class="carousel-control left" role="button" data-slide="prev">
				<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
				<span class="sr-only">Anterior</span>
			</a>
			<a href="#carousel-1" class="carousel-control right" role="button" data-slide="prev">
				<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
				<span class="sr-only">Posterior</span>
			</a>
		</div>

	</div>
</div>
<div class="row" style="margin-top:15px;">
	<div class="col-md-8 panel">
		<div class="panel-body">
			<div class="jumbotron" style="background:#FFE27E;">
				<h2><%= image_tag "logo-alfa.png"%><b> ¡Bienvenido!</b></h2>
				<p class="text-justify">Esta es la página oficial de "<i>Asistencia técnica. Raúl Campos González</i>", mediante nuestro sitio podrá avisar de forma totalmente automática y sin coste de cualquier incidencia mediante la opción <b>"Avisar"</b> en la parte superior de la barra, tanto si es un cliente nuevo como uno antiguo. </p>
			</div>
			<ul class="list-group">
				<li class="list-group-item">
					<h2><span class="glyphicon glyphicon-chevron-right"></span> ¿A qué nos dedicamos?</h2>
					<blockquote class="text-justify">Trabajamos sobre todo en la reparación de electrodomésticos de cualquier índole y de cualquier marca desde televisores hasta neveras y por otro lado a la instalación de antenas para dar soporte a TDT (televisión digital terrestre)</blockquote>
				</li>
				<li class="list-group-item">
					<h2><span class="glyphicon glyphicon-chevron-right"></span> ¿Dónde estamos?</h2>
					<blockquote class="text-justify">Estamos en Castellar de Santiago, provincia de Ciudad Real en la zona de Campo de Montiel, también trabajamos en las localidades de Valdepeñas, Torrenueva, Almuradiel, Torre de Juan Abad, Santa Cruz de Mudela y Aldeaquemada (Jaén).</blockquote>
				</li>
				<li class="list-group-item">
					<h2><span class="glyphicon glyphicon-chevron-right"></span> ¿Cómo contactar con nosotros?</h2>
					<blockquote class="text-justify">Tres opciones:
					<ul class="list-group little-margin-top">
						<%= link_to "/about_us", class:"list-group-item" do%>
							<span class="glyphicon glyphicon-hand-right"></span> <b>Por telefóno:</b> Llamando al 926 340 271 ó al 619 358 032
						<% end %>
						<%= link_to "/about_us", class:"list-group-item" do%>
							<span class="glyphicon glyphicon-hand-right"></span> <b>Por email:</b> Enviando un correo a asistencia.t@hotmail.com
						<% end %>
						<%= link_to new_notification_path, class:"list-group-item" do %>
							<span class="glyphicon glyphicon-hand-right"></span> <b>Por web:</b> Pulsando aquí.
						<% end %>
					</ul>
				</blockquote>
				</li>
			</ul>
		</div>
		<div class="panel-footer">
			<p>Sitio diseñado y desarrollado gracias a la tecnología de Ruby on Rails, Twitter Bootstrap, HTML5, CSS3 y Javascript. Cualquier incidencia o fallo por favor reportar a <i>"asistencia.t@hotmail.com"</i> gracias.</p>
			<hr>
			<%= image_tag "brands.png", class:"image-center"%>
		</div>	
	</div>
	<div class="col-md-3 col-md-offset-1">
		<%= render "partials/side_bar" %>
	</div>
</div>